# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          mkdir -p testing
          cd testing
          touch test.txt

      - name: check the file is still there
        run: |
          ls -asl
